### ISSUE TITLE
Some services left behind after deleting infrastructure on Azure

### ISSUE THREAD

**Issue by alahiff** [indigo-dc/im#225]
Quite often, but not all the time, when a group of VMs on Azure (such as a SLURM cluster) is destroyed some services actually still exist. It always seems to be a resource group with a name like rg-4507d2a0-2059-11e8-b16d-0242ac110002 containing a virtual network and a storage account.

In /var/log/im/im.log I see this:
```
# grep rg-4507d2a0-2059-11e8-b16d-0242ac110002 /var/log/im/im.log
2018-03-05 10:01:50,218 - CloudConnector - INFO - Inf ID: 4507d2a0-2059-11e8-b16d-0242ac110002: Delete RG rg-4507d2a0-2059-11e8-b16d-0242ac110002.
2018-03-05 10:03:42,440 - CloudConnector - ERROR - Inf ID: 4507d2a0-2059-11e8-b16d-0242ac110002: Error deleting Resource group rg-4507d2a0-2059-11e8-b16d-0242ac110002 (1/3).
2018-03-05 10:05:33,506 - CloudConnector - ERROR - Inf ID: 4507d2a0-2059-11e8-b16d-0242ac110002: Error deleting Resource group rg-4507d2a0-2059-11e8-b16d-0242ac110002 (2/3).
2018-03-05 10:07:09,689 - CloudConnector - ERROR - Inf ID: 4507d2a0-2059-11e8-b16d-0242ac110002: Error deleting Resource group rg-4507d2a0-2059-11e8-b16d-0242ac110002 (3/3).
2018-03-05 10:07:09,690 - CloudConnector - ERROR - Inf ID: 4507d2a0-2059-11e8-b16d-0242ac110002: Resource group rg-4507d2a0-2059-11e8-b16d-0242ac110002 cannot be deleted!!!
```
More explicitly the error is:
```
2018-03-05 10:07:09,689 - CloudConnector - ERROR - Inf ID: 4507d2a0-2059-11e8-b16d-0242ac110002: Error deleting Resource group rg-4507d2a0-2059-11e8-b16d-0242ac110002 (3/3).
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/IM/connectors/Azure.py", line 832, in delete_resource_group
    resource_client.resource_groups.delete(group_name).wait()
  File "/usr/lib/python2.7/dist-packages/msrestazure/azure_operation.py", line 529, in wait
    raise self._exception
CloudError: Operation failed with status: 'Conflict'. Details: 409 Client Error: Conflict for url: https://management.azure.com/subscriptions/<redacted>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1SRzoyRDQ1MDdEMkEwOjJEMjA1OToyRDExRTg6MkRCMTZEOjJEMDI0MkFDMTEwMDAyLVVLU09VVEgiLCJqb2JMb2NhdGlvbiI6InVrc291dGgifQ?api-version=2016-02-01
2018-03-05 10:07:09,690 - CloudConnector - ERROR - Inf ID: 4507d2a0-2059-11e8-b16d-0242ac110002: Resource group rg-4507d2a0-2059-11e8-b16d-0242ac110002 cannot be deleted!!!
```
Whenenver this happens it's possible to successfully delete the resource group using the Azure portal.

**Comment by micafer** [comment]
Hi @alahiff,
The Azure API is not very "fast" ...
The IM has made 3 tries of deleteing the RG but it seems that there are some components inside that have not been deleted yet and the deletion fails.

The infrastructure will not be set as deleted so you can try to delete it again.
If you try again it is finally deleted?

**Comment by alahiff** [comment]
Hi @micafer, 
Yes, "fast" is definitely not the word to describe the Azure API :-)

I think after this problem occurred the infrastructure was no longer being listed by IM at all (e.g. from im_client.py list), but I'll double check this.

**Comment by alahiff** [comment]
I did another test and experienced the same issue. Note that IM gives this:
```
$ im_client.py destroy 2a775380-206c-11e8-96f0-0242ac110002
Connected with: http://localhost:8899
Infrastructure successfully destroyed
```
suggesting that everything was successful, however looking in the IM log:
```
# grep rg-2a775380-206c-11e8-96f0-0242ac110002 /var/log/im/im 
2018-03-05 11:56:00,857 - CloudConnector - INFO - Inf ID: 2a775380-206c-11e8-96f0-0242ac110002: Creating Inf RG: rg-2a775380-206c-11e8-96f0-0242ac110002
2018-03-05 12:54:52,473 - CloudConnector - INFO - Inf ID: 2a775380-206c-11e8-96f0-0242ac110002: Delete RG rg-2a775380-206c-11e8-96f0-0242ac110002.
2018-03-05 12:56:29,057 - CloudConnector - ERROR - Inf ID: 2a775380-206c-11e8-96f0-0242ac110002: Error deleting Resource group rg-2a775380-206c-11e8-96f0-0242ac110002 (1/3).
2018-03-05 12:58:16,903 - CloudConnector - ERROR - Inf ID: 2a775380-206c-11e8-96f0-0242ac110002: Error deleting Resource group rg-2a775380-206c-11e8-96f0-0242ac110002 (2/3).
2018-03-05 12:59:57,580 - CloudConnector - ERROR - Inf ID: 2a775380-206c-11e8-96f0-0242ac110002: Error deleting Resource group rg-2a775380-206c-11e8-96f0-0242ac110002 (3/3).
2018-03-05 12:59:57,580 - CloudConnector - ERROR - Inf ID: 2a775380-206c-11e8-96f0-0242ac110002: Resource group rg-2a775380-206c-11e8-96f0-0242ac110002 cannot be deleted!!!
```
If I try to do another destroy it doesn't work:
```
$ im_client.py destroy 2a775380-206c-11e8-96f0-0242ac110002
Connected with: http://localhost:8899
ERROR destroying the infrastructure: Invalid infrastructure ID or access not granted.
```

**Comment by micafer** [comment]
Hi @alahiff,

I have checked the plugin and you are right.
The error are not raised and it is returned as "Infrastructure successfully destroyed" incorrectly.
We will fix it.
