### ISSUE TITLE
Docker images with tags "latest" and "1.7.2" unable to deploy on Azure

### ISSUE THREAD

**Issue by alahiff** [indigo-dc/im#236]
When using the indigodatacloud/im:latest or indigodatacloud/im:1.7.2 images the following error occurs when trying to deploy on Azure:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/IM/InfrastructureManager.py", line 1288, in CreateInfrastructure
    vms = InfrastructureManager.AddResource(inf.id, radl, auth)
  File "/usr/lib/python2.7/dist-packages/IM/InfrastructureManager.py", line 510, in AddResource
    for s in systems for s0 in cloud.concreteSystem(s, auth)]
  File "/usr/lib/python2.7/dist-packages/IM/connectors/Azure.py", line 194, in concreteSystem
    credentials, subscription_id = self.get_credentials(auth_data)
  File "/usr/lib/python2.7/dist-packages/IM/connectors/Azure.py", line 102, in get_credentials
    self.credentials = UserPassCredentials(username, password)
NameError: global name 'UserPassCredentials' is not defined
2018-05-30 11:13:19,572 - InfrastructureManager - ERROR - Error Creating Inf.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/IM/REST.py", line 477, in RESTCreateInfrastructure
    inf_id = InfrastructureManager.CreateInfrastructure(radl_data, auth, async_call)
  File "/usr/lib/python2.7/dist-packages/IM/InfrastructureManager.py", line 1310, in CreateInfrastructure
    raise e
NameError: global name 'UserPassCredentials' is not defined
```
Note that 1.7.1 is fine.

For the record this is with the INDIGO Orchestrator (I haven't checked with IM on it's own).

**Comment by micafer** [comment]
It is known bug of the 1.7.2 version.
https://github.com/grycap/im/issues/623
It is solved in the master version of the grycap IM.
You can see the solution in this commit: https://github.com/grycap/im/commit/46c7eca8958623bb389f04e91f72a30e0e4e83f0

As soon as posible I will release the new fixed version.

**Comment by micafer** [comment]
PR: #237 will fix it in this fork.

**Comment by micafer** [comment]
If you want I can "release a 1.7.2-dev" version (as I have made with the grycap IM) with a fixed version until version 1.7.3 is released.

**Comment by alahiff** [comment]
Thanks anyway, but for the moment 1.7.1 seems to be working for me.

**Comment by micafer** [comment]
Version 1.7.3 is released.
